const products = [

    {
        id: 1,
        name: "Chronos Elite Automatic",
        brand: "CHRONOVA",
        category: "Automatic",
        gender: "Men",
        price: 349,
        originalPrice: 449,
        discount: 22,
        rating: 4.9,
        reviewCount: 128,
        movement: "Automatic",
        strapMaterial: "Stainless Steel",
        caseMaterial: "316L Stainless Steel",
        caseSize: "42mm",
        waterResistance: "100m",
        glass: "Sapphire Crystal",
        dialColor: "Black",
        stock: 18,
        featured: true,
        newArrival: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 2,
        name: "Royal Heritage Gold",
        brand: "CHRONOVA",
        category: "Luxury",
        gender: "Men",
        price: 599,
        originalPrice: 749,
        discount: 20,
        rating: 4.8,
        reviewCount: 96,
        movement: "Automatic",
        strapMaterial: "Leather",
        caseMaterial: "Gold PVD Steel",
        caseSize: "41mm",
        waterResistance: "50m",
        glass: "Sapphire Crystal",
        dialColor: "Champagne",
        stock: 12,
        featured: true,
        newArrival: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 3,
        name: "Urban Steel Chronograph",
        brand: "CHRONOVA",
        category: "Chronograph",
        gender: "Men",
        price: 289,
        originalPrice: 349,
        discount: 17,
        rating: 4.7,
        reviewCount: 84,
        movement: "Quartz",
        strapMaterial: "Stainless Steel",
        caseMaterial: "Stainless Steel",
        caseSize: "44mm",
        waterResistance: "100m",
        glass: "Mineral",
        dialColor: "Blue",
        stock: 25,
        featured: true,
        newArrival: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 4,
        name: "Midnight Classic",
        brand: "CHRONOVA",
        category: "Classic",
        gender: "Men",
        price: 229,
        originalPrice: 279,
        discount: 18,
        rating: 4.8,
        reviewCount: 67,
        movement: "Quartz",
        strapMaterial: "Leather",
        caseMaterial: "Stainless Steel",
        caseSize: "40mm",
        waterResistance: "50m",
        glass: "Mineral",
        dialColor: "Black",
        stock: 31,
        featured: true,
        newArrival: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 5,
        name: "Monaco Automatic",
        brand: "CHRONOVA",
        category: "Automatic",
        gender: "Men",
        price: 479,
        originalPrice: 549,
        discount: 13,
        rating: 4.9,
        reviewCount: 142,
        movement: "Automatic",
        strapMaterial: "Leather",
        caseMaterial: "Stainless Steel",
        caseSize: "42mm",
        waterResistance: "100m",
        glass: "Sapphire Crystal",
        dialColor: "Green",
        stock: 15,
        featured: true,
        newArrival: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 6,
        name: "Prestige Black Edition",
        brand: "CHRONOVA",
        category: "Luxury",
        gender: "Men",
        price: 699,
        originalPrice: 849,
        discount: 18,
        rating: 5.0,
        reviewCount: 53,
        movement: "Automatic",
        strapMaterial: "Leather",
        caseMaterial: "Black PVD Steel",
        caseSize: "43mm",
        waterResistance: "100m",
        glass: "Sapphire Crystal",
        dialColor: "Black",
        stock: 8,
        featured: true,
        newArrival: false,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1619946794135-5bc917a27793?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 7,
        name: "Aurora Women's Watch",
        brand: "CHRONOVA",
        category: "Classic",
        gender: "Women",
        price: 249,
        originalPrice: 299,
        discount: 17,
        rating: 4.8,
        reviewCount: 71,
        movement: "Quartz",
        strapMaterial: "Stainless Steel",
        caseMaterial: "Stainless Steel",
        caseSize: "34mm",
        waterResistance: "50m",
        glass: "Mineral",
        dialColor: "White",
        stock: 27,
        featured: true,
        newArrival: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 8,
        name: "Rose Gold Elegance",
        brand: "CHRONOVA",
        category: "Luxury",
        gender: "Women",
        price: 379,
        originalPrice: 449,
        discount: 16,
        rating: 4.9,
        reviewCount: 89,
        movement: "Quartz",
        strapMaterial: "Stainless Steel",
        caseMaterial: "Rose Gold PVD",
        caseSize: "36mm",
        waterResistance: "50m",
        glass: "Sapphire Crystal",
        dialColor: "Rose",
        stock: 19,
        featured: true,
        newArrival: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1526045431048-f857369baa09?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 9,
        name: "Ocean Master",
        brand: "CHRONOVA",
        category: "Sports",
        gender: "Men",
        price: 329,
        originalPrice: 399,
        discount: 18,
        rating: 4.7,
        reviewCount: 113,
        movement: "Quartz",
        strapMaterial: "Silicone",
        caseMaterial: "Stainless Steel",
        caseSize: "45mm",
        waterResistance: "200m",
        glass: "Mineral",
        dialColor: "Blue",
        stock: 22,
        featured: true,
        newArrival: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 10,
        name: "Titanium Pro",
        brand: "CHRONOVA",
        category: "Sports",
        gender: "Men",
        price: 429,
        originalPrice: 499,
        discount: 14,
        rating: 4.8,
        reviewCount: 61,
        movement: "Automatic",
        strapMaterial: "Titanium",
        caseMaterial: "Titanium",
        caseSize: "44mm",
        waterResistance: "150m",
        glass: "Sapphire Crystal",
        dialColor: "Grey",
        stock: 13,
        featured: false,
        newArrival: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 11,
        name: "Grand Classic",
        brand: "CHRONOVA",
        category: "Classic",
        gender: "Men",
        price: 199,
        originalPrice: 249,
        discount: 20,
        rating: 4.6,
        reviewCount: 48,
        movement: "Quartz",
        strapMaterial: "Leather",
        caseMaterial: "Stainless Steel",
        caseSize: "39mm",
        waterResistance: "50m",
        glass: "Mineral",
        dialColor: "White",
        stock: 34,
        featured: false,
        newArrival: false,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=75"
    },

    {
        id: 12,
        name: "Imperial Chronograph",
        brand: "CHRONOVA",
        category: "Chronograph",
        gender: "Men",
        price: 389,
        originalPrice: 459,
        discount: 15,
        rating: 4.8,
        reviewCount: 75,
        movement: "Quartz",
        strapMaterial: "Stainless Steel",
        caseMaterial: "Stainless Steel",
        caseSize: "43mm",
        waterResistance: "100m",
        glass: "Sapphire Crystal",
        dialColor: "Silver",
        stock: 17,
        featured: false,
        newArrival: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 13,
        name: "Vintage Heritage",
        brand: "CHRONOVA",
        category: "Classic",
        gender: "Men",
        price: 279,
        originalPrice: 329,
        discount: 15,
        rating: 4.7,
        reviewCount: 55,
        movement: "Automatic",
        strapMaterial: "Leather",
        caseMaterial: "Stainless Steel",
        caseSize: "40mm",
        waterResistance: "50m",
        glass: "Mineral",
        dialColor: "Cream",
        stock: 14,
        featured: false,
        newArrival: false,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1594534475808-b18fc33b045e?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 14,
        name: "Sapphire Elite",
        brand: "CHRONOVA",
        category: "Luxury",
        gender: "Men",
        price: 799,
        originalPrice: 949,
        discount: 16,
        rating: 5.0,
        reviewCount: 37,
        movement: "Automatic",
        strapMaterial: "Leather",
        caseMaterial: "Stainless Steel",
        caseSize: "42mm",
        waterResistance: "100m",
        glass: "Sapphire Crystal",
        dialColor: "Navy",
        stock: 6,
        featured: true,
        newArrival: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&w=800&q=75"
    },

    {
        id: 15,
        name: "Executive Silver",
        brand: "CHRONOVA",
        category: "Classic",
        gender: "Men",
        price: 259,
        originalPrice: 299,
        discount: 13,
        rating: 4.6,
        reviewCount: 44,
        movement: "Quartz",
        strapMaterial: "Stainless Steel",
        caseMaterial: "Stainless Steel",
        caseSize: "40mm",
        waterResistance: "50m",
        glass: "Mineral",
        dialColor: "Silver",
        stock: 29,
        featured: false,
        newArrival: false,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&w=800&q=75"
    },

    {
        id: 16,
        name: "Celeste Pearl",
        brand: "CHRONOVA",
        category: "Classic",
        gender: "Women",
        price: 289,
        originalPrice: 349,
        discount: 17,
        rating: 4.9,
        reviewCount: 63,
        movement: "Quartz",
        strapMaterial: "Leather",
        caseMaterial: "Rose Gold PVD",
        caseSize: "35mm",
        waterResistance: "50m",
        glass: "Mineral",
        dialColor: "Pearl",
        stock: 21,
        featured: true,
        newArrival: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=800&q=75"
    },

    {
        id: 17,
        name: "Royal Lady",
        brand: "CHRONOVA",
        category: "Luxury",
        gender: "Women",
        price: 549,
        originalPrice: 649,
        discount: 15,
        rating: 4.9,
        reviewCount: 49,
        movement: "Quartz",
        strapMaterial: "Stainless Steel",
        caseMaterial: "Gold PVD",
        caseSize: "34mm",
        waterResistance: "50m",
        glass: "Sapphire Crystal",
        dialColor: "Gold",
        stock: 10,
        featured: false,
        newArrival: true,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=800&q=75"
    },

    {
        id: 18,
        name: "Apex Sport",
        brand: "CHRONOVA",
        category: "Sports",
        gender: "Men",
        price: 319,
        originalPrice: 379,
        discount: 16,
        rating: 4.7,
        reviewCount: 81,
        movement: "Quartz",
        strapMaterial: "Rubber",
        caseMaterial: "Stainless Steel",
        caseSize: "44mm",
        waterResistance: "200m",
        glass: "Mineral",
        dialColor: "Black",
        stock: 24,
        featured: false,
        newArrival: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=85"
    },

    {
        id: 19,
        name: "Noir Prestige",
        brand: "CHRONOVA",
        category: "Luxury",
        gender: "Men",
        price: 649,
        originalPrice: 799,
        discount: 19,
        rating: 4.9,
        reviewCount: 58,
        movement: "Automatic",
        strapMaterial: "Leather",
        caseMaterial: "Black PVD",
        caseSize: "42mm",
        waterResistance: "100m",
        glass: "Sapphire Crystal",
        dialColor: "Black",
        stock: 9,
        featured: true,
        newArrival: false,
        bestseller: true,
        image: "https://images.unsplash.com/photo-1619946794135-5bc917a27793?auto=format&fit=crop&w=800&q=75"
    },

    {
        id: 20,
        name: "Silver Horizon",
        brand: "CHRONOVA",
        category: "Automatic",
        gender: "Men",
        price: 459,
        originalPrice: 529,
        discount: 13,
        rating: 4.8,
        reviewCount: 72,
        movement: "Automatic",
        strapMaterial: "Stainless Steel",
        caseMaterial: "Stainless Steel",
        caseSize: "41mm",
        waterResistance: "100m",
        glass: "Sapphire Crystal",
        dialColor: "Silver",
        stock: 16,
        featured: false,
        newArrival: true,
        bestseller: false,
        image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&q=75"
    }

];